### ISSUE TITLE
Wrong viewport on Firefox for Android

### ISSUE THREAD

**Issue by ilesinge** [ilesinge/prodo#10]
On Firefox for Android, the viewport is too large, the text currently edited is barely legible.

**Comment by raphaelbastide** [comment]
Should we add a media query?

**Comment by ilesinge** [comment]
Shouldn't [viewport CSS rule](https://docs.webplatform.org/wiki/css/atrules/@viewport) or [viewport meta tag](https://docs.webplatform.org/wiki/tutorials/mobile_viewport) (something like `<meta name='viewport' content='width=device-width' />`) be sufficent?

**Comment by ilesinge** [comment]
The viewport meta tag worked.
