### ISSUE TITLE
Feature: Fully transparent iframe background

### ISSUE THREAD

**Issue by raphaelbastide** [ilesinge/prodo#12]
I thought we could make the iframe’s background fully transparent to have a real preview of the result, and find a trick to make the raw content readable. This trick can be:
- semi-transparent background color under the text (only) of the textarea. I know it is not possible but you may know a way to do that!
- Cumulated text-shadows, this is what I use for now.
- anything else?

![selection_122](https://cloud.githubusercontent.com/assets/193122/9067673/4179531e-3adf-11e5-97e5-4a4c390cb9aa.png)

**Comment by ilesinge** [comment]
I don't know any other way to do that, but I like your solution!
Maybe a little less flashy though.
I'll hack it in the next days when I find time, or submit a PR :)

**Comment by ilesinge** [comment]
Oh, and on your version, when text is selected, it's unreadable (at least in Firefox).
You may want to override the style on the [::selection](https://developer.mozilla.org/en-US/docs/Web/CSS/%3A%3Aselection) pseudo-class.

**Comment by ilesinge** [comment]
Another very-hacky hypothesis would be to have the textarea's text completely transparent, and add another layer between the iframe and the textarea, whose content would be updated in real-time by replacing \n with br tags.
It would be with display:inline; so the background would only apply to text.
I don't know if it works though.

**Comment by raphaelbastide** [comment]
For me, it makes more sense to deal with the constraint ant adopt the more adapted and less hacky solution aka the text-shadow. I kind of like that this constraint visually impact the UI. Plus if we think about it, the text-shadow is lighter and hides less information than a text background color. Also, we can just make it disappear when the text is selected. [Demo](http://write.raphaelbastide.com/?PCFET0NUWVBFIGh0bWw+CjxoZWFkPgogICAgPHNjcmlwdD4KICAgICAgICB2YXIgc2VhcmNoID0gd2luZG93LmxvY2F0aW9uLnNlYXJjaC5zcGxpdCgnPycpOwogICAgICAgIHZhciBkYXRhID0gc2VhcmNoW3NlYXJjaC5sZW5ndGggLSAxXTsKICAgICAgICBpZiAoZGF0YSkgewogICAgICAgICAgICB3aW5kb3cubG9jYXRpb24gPSAnZGF0YTp0ZXh0L2h0bWw7Y2hhcnNldD11dGYtODtiYXNlNjQsJytkYXRhOwogICAgICAgIH0KICAgIDwvc2NyaXB0PgogICAgPCEtLSBodHRwczovL2dpdGh1Yi5jb20vaWxlc2luZ2UvcHJvZG8gLS0+CiAgICA8dGl0bGU+cHJvZG88L3RpdGxlPgogICAgPGxpbmsgaHJlZj0iZGF0YTppbWFnZS9wbmc7YmFzZTY0LGlWQk9SdzBLR2dvQUFBQU5TVWhFVWdBQUFCQUFBQUFRQ0FNQUFBQW9MUTlUQUFBQVZGQk1WRVVBQUFBN0hUaExLbFZaTUdka1RaNSthSEtva3B6eTZ0bnk4ZlB6OGZQejh2VDA4dkwxOC9QMTgvWDI5UFQyOWZYMjlmYjI5dmIzOWZmMzl2ajU5L241K1BmNitmajYrdm43Ky9yOCsvdjgvUHYvLy8rVGZNTVlBQUFBQVhSU1RsTUFRT2JZWmdBQUFHRkpSRUZVR0JrRndUR0tBZ0VRQU1HYVpkeEFFQXo4L3c4RmswdUUyN1pxbkFDK01HNnZhZUk5ZlhGUVZiblBpWU9xaXZ1Y0xFbjRJdzZxcXVmTVlGVkNEejRzQVlBbEFMQmM0Qm9HeXo4UXNGelR4QUJMQ1FHckFJaFZBTVFZQU1nUFJNTTZLRnE2QjYwQUFBQUFTVVZPUks1Q1lJST0iIHJlbD0iaWNvbiIgdHlwZT0iaW1hZ2UvcG5nIiAvPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCIgLz4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04IiAvPgogICAgPHN0eWxlPgogICAgICAgIGJvZHkgewogICAgICAgICAgICBtYXJnaW46IDA7CiAgICAgICAgICAgIHBhZGRpbmc6IDA7CiAgICAgICAgICAgIGJhY2tncm91bmQ6d2hpdGU7CiAgICAgICAgfQogICAgICAgIHRleHRhcmVhIHsKICAgICAgICAgICAgZm9udC1mYW1pbHk6IG1vbm9zcGFjZTsKICAgICAgICAgICAgcG9zaXRpb246IGFic29sdXRlOwogICAgICAgICAgICBib3gtc2l6aW5nOiBib3JkZXItYm94OwogICAgICAgICAgICBvdmVyZmxvdzogYXV0bzsKICAgICAgICAgICAgbWFyZ2luOjA7CiAgICAgICAgICAgIG91dGxpbmU6IDA7CiAgICAgICAgICAgIHJlc2l6ZTogbm9uZTsKICAgICAgICAgICAgd2lkdGg6IGNhbGMoMTAwJSAtIDIwcHgpOwogICAgICAgICAgICBoZWlnaHQ6IGNhbGMoMTAwJSAtIDIwcHgpOwogICAgICAgICAgICBib3JkZXI6IG5vbmU7CiAgICAgICAgICAgIHotaW5kZXg6IDEwOwogICAgICAgICAgICBiYWNrZ3JvdW5kOiBub25lOwogICAgICAgICAgICBwYWRkaW5nOiAzMHB4IDAgMTBweCAxMHB4OwogICAgICAgICAgICBtYXJnaW46IDAgMjBweCAyMHB4IDA7CiAgICAgICAgICAgIHRleHQtc2hhZG93OiAjZmZmIDBweCAwcHggMXB4LCNmZmYgMHB4IDBweCAxcHgsI2ZmZiAwcHggMHB4IDFweCwjZmZmIDBweCAwcHggMXB4LCNmZmYgMHB4IDBweCAxcHgsCiAgICAgICAgICAgICAgICAgICAgICAgICAjZmZmIDBweCAwcHggMXB4LCNmZmYgMHB4IDBweCAxcHgsI2ZmZiAwcHggMHB4IDVweCwjZmZmIDBweCAwcHggNXB4LCNmZmYgMHB4IDBweCA1cHgsI2ZmZiAwcHggMHB4IDVweDsKICAgICAgICB9CiAgICAgICAgYSB7CiAgICAgICAgICAgIGRpc3BsYXk6IG5vbmU7CiAgICAgICAgICAgIHBvc2l0aW9uOiBmaXhlZDsKICAgICAgICAgICAgei1pbmRleDogMjA7CiAgICAgICAgICAgIGZvbnQtZmFtaWx5OiBtb25vc3BhY2U7CiAgICAgICAgICAgIHJpZ2h0OiAwOwogICAgICAgICAgICB0b3A6IDA7CiAgICAgICAgICAgIGJhY2tncm91bmQtY29sb3I6IGJsYWNrOwogICAgICAgICAgICBwYWRkaW5nOiAxMHB4IDE1cHg7CiAgICAgICAgICAgIHRleHQtZGVjb3JhdGlvbjogbm9uZTsKICAgICAgICAgICAgdGV4dC10cmFuc2Zvcm06IHVwcGVyY2FzZTsKICAgICAgICAgICAgY29sb3I6IHdoaXRlOwogICAgICAgICAgICBmb250LXNpemU6MWVtOwogICAgICAgICAgICBsZXR0ZXItc3BhY2luZzoycHg7CiAgICAgICAgICAgIG9wYWNpdHk6IDAuNTsKICAgICAgICAgICAgdHJhbnNpdGlvbjogb3BhY2l0eSAuMnM7CiAgICAgICAgfQogICAgICAgIGE6aG92ZXIsIGE6Zm9jdXMgewogICAgICAgICAgICBvcGFjaXR5OiAxOwogICAgICAgIH0KICAgICAgICBhOmFjdGl2ZSB7CiAgICAgICAgICAgIGNvbG9yOiAjY2NjOwogICAgICAgIH0KICAgICAgICBpZnJhbWUgewogICAgICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgICAgICAgICAgIHdpZHRoOiAxMDAlOwogICAgICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgICAgICAgIGJvcmRlcjogMDsKICAgICAgICB9CiAgICAgICAgOjpzZWxlY3Rpb24gewogICAgICAgICAgYmFja2dyb3VuZDpyZ2IoMCwgMCwgMCk7CiAgICAgICAgICB0ZXh0LXNoYWRvdzpub25lOwogICAgICAgICAgY29sb3I6d2hpdGU7CiAgICAgICAgICB9CiAgICAgICAgOjotbW96LXNlbGVjdGlvbiB7CiAgICAgICAgICBiYWNrZ3JvdW5kOnJnYigwLCAwLCAwKTsKICAgICAgICAgIHRleHQtc2hhZG93Om5vbmU7CiAgICAgICAgICBjb2xvcjp3aGl0ZTsKICAgICAgICAgIH0KICAgIDwvc3R5bGU+CjwvaGVhZD4KPGEgaWQ9ImxpbmsiIHRhYmluZGV4PSIyIj5saW5rPC9hPgo8aWZyYW1lIGlkPSJpZnJhbWUiPjwvaWZyYW1lPgo8dGV4dGFyZWEgdGFiaW5kZXg9IjEiIGlkPSJjb250ZW50IiBvbmlucHV0PSJ1cGRhdGVMaW5rKCkiPjwvdGV4dGFyZWE+CjxzY3JpcHQ+CiAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnY29udGVudCcpLmZvY3VzKCk7CiAgICBmdW5jdGlvbiB1cGRhdGVMaW5rKCkgewogICAgICAgIHZhciB0ZXh0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2NvbnRlbnQnKTsKICAgICAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnaWZyYW1lJykuc3JjZG9jID0gdGV4dC52YWx1ZTsKICAgICAgICB2YXIgYmFzZTY0ID0gd2luZG93LmJ0b2EodW5lc2NhcGUoZW5jb2RlVVJJQ29tcG9uZW50KHRleHQudmFsdWUpKSk7CiAgICAgICAgdmFyIHRpdGxlID0gZG9jdW1lbnQuZ2V0RWxlbWVudHNCeVRhZ05hbWUoJ3RpdGxlJylbMF07CiAgICAgICAgdmFyIHVybCA9ICc/JytiYXNlNjQ7CiAgICAgICAgdmFyIGEgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbGluaycpOwogICAgICAgIGlmICh0ZXh0LnZhbHVlID09PSAiIikgewogICAgICAgICAgdGl0bGUuaW5uZXJIVE1MID0gJ3Byb2RvJzsKICAgICAgICB9ZWxzZSB7CiAgICAgICAgICB0aXRsZS5pbm5lckhUTUwgPSB0ZXh0LnZhbHVlLnN1YnN0cmluZygwLCA2MCk7CiAgICAgICAgfQogICAgICAgIGEuc3R5bGUuZGlzcGxheSA9ICdibG9jayc7CiAgICAgICAgYS5ocmVmID0gdXJsOwogICAgfQo8L3NjcmlwdD4K)*

 \* prodo inception ;–)

**Comment by ilesinge** [comment]
Solution approved :)
=> I used a bit more shadows, I blackened text (for readability) and I softened the selection style.
Before:
![before](https://cloud.githubusercontent.com/assets/501674/9152775/2d2e8730-3e36-11e5-81cc-5a7a9faae701.png)
After:
![after](https://cloud.githubusercontent.com/assets/501674/9152776/3effd9d2-3e36-11e5-939b-1d87ee6d3b61.png)

**Comment by ilesinge** [comment]
The selection problem is still present in Chrome though, because apparently, only for textareas, text-shadow resetting is not supported in the ::selection pseudo-class...
