### ISSUE TITLE
Iframe scroll is unreachable

### ISSUE THREAD

**Issue by raphaelbastide** [ilesinge/prodo#13]
If the page excess the viewport’s height the a scroll appears in y on the iframe but it is unreachable in edit mode.

**Comment by ilesinge** [comment]
This is a real problem. Do you think leaving some pixels on the right for the iframe's scrollbar would be OK ?

**Comment by raphaelbastide** [comment]
It could. How many pixels? I guess all the scrollbars doesn’t have the same width…

**Comment by ilesinge** [comment]
Good point. Apparently 20px is good enough. For me the bug is fixed with https://github.com/ilesinge/prodo/commit/e96e4ef2e576ca14d8d275704b061fa066df709d

**Comment by raphaelbastide** [comment]
I suggest a `height: calc(100% - 20px); margin: 0 20px 20px 0;` to ensure horizontal scroll will be accessible as well.

**Comment by ilesinge** [comment]
You're right! Additional fix made.
