### ISSUE TITLE
Typographic mess

### ISSUE THREAD

**Issue by raphaelbastide** [ilesinge/prodo#5]
If user don’t quickly jump some lines at the begining of the redaction, this happens:

![selection_116](https://cloud.githubusercontent.com/assets/193122/9048906/08768106-3a3d-11e5-96ee-915d56d9bead.png)

On my copy, I set an extra padding top to the textarea (for now) to avoid this. But I think we can find other ideas.

![selection_115](https://cloud.githubusercontent.com/assets/193122/9048920/287a0414-3a3d-11e5-9c73-739bedcbc85e.png)

This can inform clearly on what happens when the first characters are written.

**Comment by raphaelbastide** [comment]
Spit the screen can be a solution, but I must admit I like this “layer” layout!

**Comment by ilesinge** [comment]
I clearly prefer the first solution too :)

**Comment by ilesinge** [comment]
The padding solution has been applied. But I'm open if you find any better solution :)
